version: "3"

services:
  redis:
    image: "redis"
    container_name: "support_redis"
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "1300:80"
    volumes:
      - static_volume:/home/app/staticfiles
    depends_on:
      - app
    restart: "on-failure"

  postgres:
    image: "postgres:15"
    container_name: "support_db"
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    command: sh -c "python ./src/manage.py makemigrations &&
                    python ./src/manage.py migrate &&
                    python ./src/manage.py collectstatic --noinput&&
                    gunicorn src.config.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    image: "support_app"
    container_name: "support_app"
    env_file: ".env"
    depends_on:
      - "postgres"
    volumes:
      - ".:/app:rw"
      - "static_volume:/staticfiles"
    ports:
      - "8000:8000"

volumes:
  pg_data: {}
  static_volume: {}