[tool.black]
target-version = ['py39']
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
                     # the root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = '.venv,venv,env,migrations'
src_paths = []

[tool.mypy]
plugins = [
    'mypy_django_plugin.main',
    'mypy_drf_plugin.main'
]
python_version = '3.10'
mypy_path = 'src'
files = ['*.py',]
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true
check_untyped_defs = true

# Silint "type import errors" as our 3rd-party libs does not have types
# Check: https://mypy.readthedocs.io/en/latest/config_file.html#import-discovery
follow_imports = 'silent'

[[tool.mypy.overrides]]
module = [
    'mixer.*',
    'rest_framework_simplejwt.views.*'
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings"
