name: Check code quality

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pipenv
      run:
        python -m pip install --upgrade pip && pip install pipenv
    - name: Install deps
      run:
        pipenv sync --system
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
          max-line-length: "100"
          exclude: "src/config/settings.py"
    - name: Run formatters
      run: black --check . && isort --check .
